version: '3.8'

services:
  app:
    build: .
    container_name: transcription_api
    ports:
      - "3000:3000"
    environment:
      # L'hôte de la base de données devient le nom du service "db" (PostgreSQL)
      - DATABASE_URL=postgresql://postgres:Freddy1243.@db:5432/transcription_db
      # On récupère la clé depuis le fichier .env de l'hôte
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db
    volumes:
      # Pour conserver les téléchargements et PDF même si le conteneur redémarre
      - ./downloads:/usr/src/app/downloads
      - ./outputs:/usr/src/app/outputs
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: transcription_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Freddy1243.
      - POSTGRES_DB=transcription_db
    ports:
      - "5432:5432"
    volumes:
      # Persistance de la base de données
      - postgres_data:/var/lib/postgresql/data
      # Exécute automatiquement init.sql à la création de la base
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: